runtime:
  name: "pen-shop-agents"
  
model:
  provider: "ollama"
  endpoint: "http://model-runner:11434"
  model: "qwen2.5:3b"

mcp_servers:
  pen_catalog:
    url: "http://pen-catalog-mcp:3001"
    transport: "http"

agents:
  sales_agent:
    name: "Pen Sales Assistant"
    description: "Helps customers buy pens"
    mcp_servers: ["pen_catalog"]
