services:
  # Pen Shop Frontend
  pen-front-end:
    image: nginxinc/nginx-unprivileged:alpine
    ports:
      - "9091:8080"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - pen-shop-network

  # Pen Catalog HTTP API (like sock-shop catalogue)
  pen-catalogue:
    build: ./pen-catalogue
    ports:
      - "9092:8080"
    environment:
      - PORT=8080
    networks:
      - pen-shop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Gateway - Following Sock-Shop Pattern
  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - MCP_GATEWAY_PORT=8080
    command:
      - --transport=sse
      - --port=8080
      - --servers=fetch,brave,mongodb,curl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pen-shop-network
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB for MCP servers
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=penstore
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - pen-shop-network

networks:
  pen-shop-network:
    driver: bridge

volumes:
  mongodb_data:
