
services:
  # Custom Pen Store Frontend
  pen-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    hostname: pen-frontend
    ports:
      - 9090:80
    restart: always
    environment:
      - CATALOGUE_SERVICE_HOST=pen-catalogue
      - CATALOGUE_SERVICE_PORT=8081
      - API_BASE_URL=http://pen-catalogue:8081
    depends_on:
      - pen-catalogue
    networks:
      - pen-shop-network

  # Custom Pen Catalogue Service
  pen-catalogue:
    build:
      context: ./catalogue-service
      dockerfile: Dockerfile
    hostname: pen-catalogue
    restart: always
    ports:
      - 8081:8081
    environment:
      - MYSQL_HOST=catalogue-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=pendb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    depends_on:
      - catalogue-db
    networks:
      - pen-shop-network

  # MySQL Database for Pen Catalogue
  catalogue-db:
    image: mysql:8.0
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=pendb
      - MYSQL_USER=penuser
      - MYSQL_PASSWORD=penpass
    volumes:
      - ./data/mysql-init:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - pen-shop-network

  # MongoDB for Reviews and Agent Data
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=penstore
    volumes:
      - ./data/mongodb-init:/docker-entrypoint-initdb.d:ro
      - mongodb_data:/data/db
    command: [mongod, --quiet, --logpath, /var/log/mongodb/mongod.log, --logappend]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pen-shop-network

  # Agent UI (React App)
  adk-ui:
    build:
      context: ./adk-ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_STORE_NAME=Moby Pen Shop
      - REACT_APP_CATALOGUE_URL=http://localhost:8081
    depends_on:
      - adk-backend
    networks:
      - pen-shop-network

  # Agent Backend (Go with ADK)
  adk-backend:
    build:
      context: ./adk-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/mcp
      - CATALOGUE_URL=http://pen-catalogue:8081
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/penstore?authSource=admin
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - AI_DEFAULT_MODEL=openai/gpt-4
      - MODEL_RUNNER_URL=${MODEL_RUNNER_URL:-http://model-runner:8080}
      - MODEL_RUNNER_MODEL=${MODEL_RUNNER_MODEL:-qwen3}
    depends_on:
      - mcp-gateway
      - pen-catalogue
      - mongodb
    volumes:
      - ./secret.openai-api-key:/run/secrets/openai-api-key:ro
    networks:
      - pen-shop-network

  # MCP Gateway with Interceptors
  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - 8811:8811
    use_api_socket: true
    command:
      - --transport=streaming
      - --servers=fetch,brave,curl,mongodb
      - --config=/mcp_config
      - --verbose
      - --interceptor=before:exec:/interceptors/pen-price-guard.sh
      - --interceptor=after:exec:/interceptors/data-protector.sh
    configs:
      - mcp_config
    volumes:
      # Mount interceptors directory
      - ./interceptors:/interceptors:ro
      # Session state for interceptors
      - /tmp:/tmp
      # Docker socket for container management
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
    networks:
      - pen-shop-network

  # Optional: Model Runner for local AI models
  model-runner:
    image: docker/model-runner:latest
    ports:
      - 8080:8080
      - 9091:9090  # Changed from 9090 to avoid conflict with pen-frontend
    environment:
      - LOG_LEVEL=debug
      - ENABLE_GPU=false  # Set to true if you have GPU
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - model-cache:/models
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:8080/health']
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - pen-shop-network
    profiles:
      - with-model-runner  # Optional: only start with --profile with-model-runner

# Networks
networks:
  pen-shop-network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  model-cache:
    driver: local

# Configs section
configs:
  mcp_config:
    content: |
      mongodb:
        connection_string: mongodb://admin:password@mongodb:27017/penstore?authSource=admin
      brave:
        api_key: ${BRAVE_API_KEY:-your_brave_key_here}

# Models configuration (for Docker Desktop with model runner)
models:
  qwen3:
    model: ai/qwen3:14B-Q6_K
    context_size: 32768

# Secrets (if you prefer using secrets instead of files)
secrets:
  openai-api-key:
    file: secret.openai-api-key
