# 🖊️ Pen Shop Sequential Multi-Agent System
# Based on Docker ADK Sock Shop Pattern

services:
  # Pen Store Frontend (unchanged)
  pen-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    hostname: pen-frontend
    ports:
      - 9090:80
    restart: always
    environment:
      - CATALOGUE_SERVICE_HOST=pen-catalogue
      - CATALOGUE_SERVICE_PORT=8081
      - API_BASE_URL=http://pen-catalogue:8081
      - ADK_API_BASE_URL=http://adk-backend:8000
    depends_on:
      - pen-catalogue
      - adk-backend

  # Pen Catalogue Service (unchanged)
  pen-catalogue:
    build:
      context: ./catalogue-service
      dockerfile: Dockerfile
    hostname: pen-catalogue
    restart: always
    ports:
      - 8081:8081
    environment:
      - MYSQL_HOST=catalogue-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=pendb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    depends_on:
      - catalogue-db

  # MySQL Database (unchanged)
  catalogue-db:
    image: mysql:8.0
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=pendb
      - MYSQL_USER=penuser
      - MYSQL_PASSWORD=penpass
    volumes:
      - ./data/mysql-init:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  # Agent UI (Enhanced for Multi-Agent)
  adk-ui:
    build:
      context: ./adk-ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_STORE_NAME=Moby Pen Shop - Sequential AI Agents
      - REACT_APP_CATALOGUE_URL=http://localhost:8081
      - REACT_APP_AGENT_MODE=sequential
      - REACT_APP_SHOW_AGENT_DEBUG=true
    depends_on:
      - adk-backend

  # Sequential Agent Backend (Main Service)
  adk-backend:
    build:
      context: ./adk-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      # Agent Configuration
      - AGENT_MODE=sequential
      - SEQUENTIAL_AGENT_ENABLED=true
      
      # AI Model Configuration
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - AI_DEFAULT_MODEL=openai/gpt-4
      
      # External Services
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
      - CATALOGUE_URL=http://pen-catalogue:8081
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/penstore
      
      # Logging
      - LOG_LEVEL=info
      - DEBUG_AGENTS=true
      
    depends_on:
      - mcp-gateway
      - pen-catalogue
      - mongodb
    secrets:
      - openai-api-key
    models:
      qwen3:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Gateway (Security & Tool Layer)
  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - 8811:8811
    use_api_socket: true
    command:
      - --transport=sse
      - --servers=fetch,brave,curl,mongodb,pen-research
      - --config=/mcp_config
      - --verbose
      - --rate-limit=100
    configs:
      - mcp_config
    depends_on:
      - mongodb

  # MongoDB for Reviews and AI Data (unchanged)
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=penstore
    volumes:
      - ./data/mongodb-init:/docker-entrypoint-initdb.d:ro
      - mongodb_data:/data/db
    command: [mongod, --quiet, --logpath, /var/log/mongodb/mongod.log, --logappend]
    healthcheck:
      test: [CMD, mongosh, --eval, "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

models:
  qwen3:
    model: ai/qwen3:14B-Q6_K
    context_size: 32768

volumes:
  mysql_data:
  mongodb_data:

configs:
  mcp_config:
    content: |
      mongodb:
        connection_string: mongodb://admin:password@mongodb:27017/penstore
      brave:
        api_key: ${BRAVE_API_KEY}
      pen-research:
        catalogue_url: http://pen-catalogue:8081
        research_depth: comprehensive

secrets:
  openai-api-key:
    file: secret.openai-api-key
