
services:
  # Pen Shop Frontend (Secure)
  pen-frontend-secure:
    build: ./pen-shop/frontend
    ports:
      - "8081:80"
    environment:
      - API_URL=http://localhost:3001
    depends_on:
      - adk-secure
    networks:
      - pen-secure-network

  # Agent Development Kit (Secure)
  adk-secure:
    build:
      context: ./adk
      dockerfile: Dockerfile
    ports:
      - "3001:8000"
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway-secure:8811/sse
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - AI_DEFAULT_MODEL=openai/gpt-4
      - SECURITY_ENABLED=true
      - PEN_DB_URL=mongodb://penstore_user:${SECURE_DB_PASSWORD}@mongodb-secure:27017/penstore
    depends_on:
      - mcp-gateway-secure
      - mongodb-secure
    secrets:
      - openai-api-key
    networks:
      - pen-secure-network

  # MCP Gateway (Secure - With Filters and Restrictions)
  mcp-gateway-secure:
    image: docker/mcp-gateway:latest
    ports:
      - "8812:8811"
    command:
      - --transport=sse
      - --servers=fetch,curl,mongodb
      - --config=/mcp_config
      - --secrets=docker-desktop:/run/secrets/mcp_secret
      - --verbose
      - --security=enabled
      - --rate-limit=100
      - --input-filter=enabled
      - --output-filter=enabled
    configs:
      - mcp_config_secure
    secrets:
      - mcp_secret
    depends_on:
      - mongodb-secure
    networks:
      - pen-secure-network
      - mcp-internal-network

  # MongoDB (Secure - Limited permissions)
  mongodb-secure:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${SECURE_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=penstore
    volumes:
      - ./data/mongodb-secure:/docker-entrypoint-initdb.d:ro
      - mongodb_secure_data:/data/db
    command: [mongod, --quiet, --auth]
    networks:
      - mcp-internal-network
    security_opt:
      - no-new-privileges:true

  # Security Monitor
  security-monitor:
    build: ./monitoring/security-monitor
    ports:
      - "9001:3000"
    environment:
      - MCP_GATEWAY_URL=http://mcp-gateway-secure:8811
    depends_on:
      - mcp-gateway-secure
    networks:
      - pen-secure-network

volumes:
  mongodb_secure_data:

networks:
  pen-secure-network:
    driver: bridge
  mcp-internal-network:
    internal: true

configs:
  mcp_config_secure:
    content: |
      # Secure configuration with restrictions
      mongodb:
        connection_string: mongodb://penstore_user:${SECURE_DB_PASSWORD}@mongodb-secure:27017/penstore
        allowed_collections: ["pens", "orders"]
        forbidden_operations: ["drop", "createUser", "dropUser"]
        read_only_collections: ["audit_log"]
      
      fetch:
        allowed_domains: ["api.example.com", "cdn.example.com"]
        blocked_private_ips: true
        max_response_size: 1MB
        timeout: 10s
      
      curl:
        allowed_protocols: ["https"]
        blocked_private_networks: true
        ssl_verify: true
        max_redirects: 3

secrets:
  openai-api-key:
    file: secret.openai-api-key
  mcp_secret:
    file: ./.mcp.env
