version: '3.8'

services:
  # Pen Shop Frontend
  pen-frontend-vulnerable:
    build: ./pen-shop/frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://localhost:3000
    depends_on:
      - adk-vulnerable
    networks:
      - pen-network

  # Agent Development Kit (Vulnerable)
  adk-vulnerable:
    build:
      context: ./adk
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway-vulnerable:8811
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - AI_DEFAULT_MODEL=openai/gpt-4
      - SECURITY_ENABLED=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mcp-gateway-vulnerable
      - mongodb
    networks:
      - pen-network

  # MCP Gateway (Vulnerable - Correct syntax)
  mcp-gateway-vulnerable:
    image: docker/mcp-gateway:latest
    ports:
      - "8811:8811"
    command:
      - --transport=sse
      - --servers=fetch,curl,mongodb
      - --config=/mcp_config
      - --verbose
    configs:
      - mcp_config_vulnerable
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/penstore?authSource=admin
    depends_on:
      - mongodb
    networks:
      - pen-network

  # MongoDB (Contains sensitive pen shop data)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=penstore
    volumes:
      - ./data/mongodb:/docker-entrypoint-initdb.d:ro
      - mongodb_data:/data/db
    command: [mongod, --quiet, --logpath, /var/log/mongodb/mongod.log, --logappend]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pen-network

volumes:
  mongodb_data:

networks:
  pen-network:
    driver: bridge

configs:
  mcp_config_vulnerable:
    content: |
      # Vulnerable MCP configuration
      mongodb:
        connection_string: mongodb://admin:password@mongodb:27017/penstore?authSource=admin
        database: penstore
      
      fetch:
        user_agent: "MCP-Fetch/1.0"
        timeout: 30
      
      curl:
        timeout: 30
        user_agent: "MCP-Curl/1.0"
